convert cent based fields to major currency unit based
fivetran/dbt_stripe_source pull request #87
Opened 2024-12-18 18:43 UTC by fivetran-reneeli

to be completed

2025-01-06 16:21 UTC, fivetran-joemarkiewicz commented on models/stg_stripe__balance_transaction.sql
> +
Would it make more sense to make this a macro and then apply the macro to each field that requires this update throughout the package. This way if we want to make this more dynamic in the future, we'll be able to maintain that more easily?

2025-01-06 16:23 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +To disable this default conversion, refer to the [README]((https://github.com/fivetran/dbt_stripe_source?tab=readme-ov-file#disabling-cent-to-dollar-conversion)) on disabling the `stripe__amount_divi
We should add a note here to detail why a customer may want to disable this functionality. Also, we should also link to [this feature request](https://github.com/fivetran/dbt_stripe/issues/102) if customers find this is not enough support for them

2025-01-06 16:24 UTC, fivetran-joemarkiewicz commented on README.md
> +Amount-based fields, such as `amount` and `net`, are typically displayed in the smallest denomination (e.g., cents for USD). By default, these values are automatically converted to dollars by dividin
Similar to the note in the CHANGELOG, we should add a note here detailing why a customer may want to disable this feature.

2025-01-06 16:24 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- This package assumes that amount-based fields, which as raw values are represented in the smallest denomination in Stripe, are cent-based. This PR shifts the existing conversion from cents to dolla
Can you highlight how this differs from how this package treated this previously.

2025-01-06 16:26 UTC, fivetran-joemarkiewicz commented on models/stg_stripe.yml
> +        description: Amount intended to be collected by this payment. A positive integer representing how much to charge in the major currency unit (e.g., 1 equals a charge of $1.00 or a charge ¥100,
These read a bit confusing when talking about the ¥ charge. Maybe we should add here that if you're currency does not contain decimal units then you should leverage the variable to turn off the division.

2025-01-06 16:27 UTC, fivetran-joemarkiewicz commented on models/stg_stripe.yml
> +        description: Gross amount of the transaction, in currency units.
What does currency units refer to in this context? For some reason this makes me think whole number which I know is not correct.

2025-01-06 16:28 UTC, fivetran-joemarkiewicz commented on README.md
Can you also address Issue #86 in this PR since it's such a small update.

2025-01-07 19:40 UTC, fivetran-reneeli commented on models/stg_stripe.yml
> +        description: Amount intended to be collected by this payment. A positive integer representing how much to charge in the major currency unit (e.g., 1 equals a charge of $1.00 or a charge ¥100,
I updated the language and pulled it into the docs.md file to avoid repetition, and added `"{{ doc('convert_values') }}"` at the end of every description for all amount-based fields. Let me know what you think

2025-01-07 19:46 UTC, fivetran-reneeli commented on models/stg_stripe.yml
> +        description: Gross amount of the transaction, in currency units.
I updated the documentation so that this is addressed by `{{ doc('convert_values') }}` referencing the docs.md. Lmk your thoughts about the language.

2025-01-07 19:48 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- This package assumes that amount-based fields, which as raw values are represented in the smallest denomination in Stripe, are cent-based. This PR shifts the existing conversion from cents to dolla
updated

2025-01-07 19:48 UTC, fivetran-reneeli commented on README.md
> +Amount-based fields, such as `amount` and `net`, are typically displayed in the smallest denomination (e.g., cents for USD). By default, these values are automatically converted to dollars by dividin
added

2025-01-07 19:48 UTC, fivetran-reneeli commented on CHANGELOG.md
> +To disable this default conversion, refer to the [README]((https://github.com/fivetran/dbt_stripe_source?tab=readme-ov-file#disabling-cent-to-dollar-conversion)) on disabling the `stripe__amount_divi
added!

2025-01-07 19:50 UTC, fivetran-reneeli commented on models/stg_stripe__balance_transaction.sql
> +
Great point! I made a macro called `convert_values` which contains the conditional division and also allows for aliasing in case the field also gets renamed.

2025-01-10 18:38 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for these edits, a few more comments in the review. Thanks!

2025-01-10 18:38 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +# dbt_stripe_source v0.13.0
Same note from the transform, let's update the changelog accordingly given the new default state of the new variable (false).

2025-01-10 18:38 UTC, fivetran-joemarkiewicz commented on models/docs.md
> +{%- enddocs %}
Let's update this to reflect the new default state

2025-01-10 18:38 UTC, fivetran-joemarkiewicz commented on macros/convert_values.sql
> +{% macro convert_values(field_name, divide_by=100.0, divide_var='stripe__convert_values', alias=None) %}
Also, we will need to make sure this default state is false following our conversation from the transform PR.

2025-01-13 23:27 UTC, fivetran-reneeli commented on models/docs.md
> +{%- enddocs %}
updated

2025-01-13 23:27 UTC, fivetran-reneeli commented on CHANGELOG.md
> +# dbt_stripe_source v0.13.0
updated

2025-01-13 23:30 UTC, fivetran-reneeli commented on macros/convert_values.sql
With the default being False now, I tried the following but it kept giving me the opposite result (setting stripe__convert_values to False or not configuring it would render `/100.0`, whereas setting to True wouldn't. So I only was able to get it to work by explicitly calling out `{% if divide_var == true %}`.

```
{% macro convert_values(field_name, divide_by=100.0, divide_var='stripe__convert_values', alias=None) %}
    {% if var(divide_var, False) %}
        {{ field_name }} as {{ alias if alias else field_name }}
    {% else %}
        {{ field_name }} / {{ divide_by }} as {{ alias if alias else field_name }}
    {% endif %}
{% endmacro %}

2025-01-15 17:39 UTC, fivetran-joemarkiewicz requested changes
A few remaining comments before approval. Let me know if you have any questions.

2025-01-15 17:39 UTC, fivetran-joemarkiewicz commented on macros/convert_values.sql
Thanks for sharing, I just tried the following version of the code and it worked as expected.
```sql
{% macro convert_values(field_name, divide_by=100.0, divide_var=var('stripe__convert_values',false), alias=None) %}
    {% if divide_var %}
        {{ field_name }} / {{ divide_by }} as {{ alias if alias else field_name }}
    {% else %}
        {{ field_name }} as {{ alias if alias else field_name }}
    {% endif %}
{% endmacro %}

```

Do you see this working on your end?

2025-01-15 17:49 UTC, fivetran-joemarkiewicz commented on README.md
> +    version: [">=0.13.0", "<0.14.0"]
This is no longer necessary given it's a patch update now.

2025-01-16 16:10 UTC, fivetran-reneeli reviewed
Thanks @fivetran-joemarkiewicz , changed applied

2025-01-16 16:10 UTC, fivetran-reneeli commented on macros/convert_values.sql
That does, that's true that the `== true` is implicit and can be removed. Just checked with true, false, and no config and the outputs were as expected.

2025-01-17 22:35 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli a few more change suggestions and notes before approval. The largest change is the request to make the macro more dynamic via the adapter.dispatch and then namespace references. Also, this will need to be a breaking change. See my notes below.

2025-01-17 22:35 UTC, fivetran-joemarkiewicz commented on models/stg_stripe__credit_note.sql
> +        {{ convert_values('amount') }},
Given the previous comment, can we also update these to include the package namespace.

```suggestion
        {{ stripe_source.convert_values('amount') }},
```

2025-01-17 22:35 UTC, fivetran-joemarkiewicz commented on models/stg_stripe__credit_note.sql
> +        {{ convert_values('amount') }},
Apply the same update for all macro call instances.

2025-01-21 17:28 UTC, fivetran-reneeli commented on CHANGELOG.md
> +# dbt_stripe_source v0.12.2
Ahh that's true.

2025-01-21 21:26 UTC, fivetran-reneeli commented on README.md
upgraded

2025-01-21 21:27 UTC, fivetran-reneeli commented on macros/convert_values.sql
> +{% endmacro %}
yes!

2025-01-21 21:27 UTC, fivetran-reneeli commented on models/stg_stripe__credit_note.sql
> +        {{ convert_values('amount') }},
done!

2025-01-21 22:54 UTC, fivetran-reneeli commented on macros/convert_values.sql
> +{% endmacro %}
updated the macro, let me know if you have any questions

2025-01-22 19:55 UTC, fivetran-joemarkiewicz approved these changes
LGTM!

2025-01-22 20:37 UTC, fivetran-jamie commented on models/stg_stripe.yml
> +        description: Gross amount of the transaction. "{{ doc('convert_values') }}"
I've never thought of using `doc` blocks in this way, neat!

2025-01-22 21:53 UTC, fivetran-jamie approved these changes
LGTM

2025-01-22 22:11 UTC, merged